---

- name: Force handlers of dependencies if required
  meta: flush_handlers

- name: Update CA certs
  ansible.builtin.command: "{{item}}"
  with_items:
   - yum -y install ca-certificates
   - /bin/update-ca-trust
